spring:
  application:
    name: yf-exam-lite
  profiles:
      active: dev
  main:
    allow-bean-definition-overriding: true
server:
  port: 8101
  # 启用服务端压缩
  compression:
    enabled: true
    min-response-size: 10
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

